### PR TITLE
Fix #10 Possibility to configure response headers

### LINKED ISSUE #10: Ability to configure headers in response
Hi, I am curious is there planned possibility to configure headers of response dynamically?

We are looking for mock api server to e2e test Angular app driven by protractor replacing rails backend with mock server.

First problem we faced - CORS.

XMLHttpRequest cannot load http://localhost:7000/v2/site.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:9500' is therefore not allowed access.

And furthermore we are doing header token authentication there so we will need ability to do header manipulations in responses.

http://www.mock-server.com/ looks to be able to provide all this, but it is too humongous.

So is it planned on some observable future?

### PR DESCRIPTION
**Pull request by clempat**
This should fix #10. I am not use with CoffeeScript. I hope it still ok.

### CODE REVIEW

**Comment by clempat** [comment]
It could be an option to add the possibility to write a function passing req to mirror some req header.

**Comment by eraserhd** [comment]
Looks good to me.  Sorry about the delay.

**Comment by eraserhd** [comment]
0.4.6 published.

**Comment by danielantelo** [comment]
How do you configure the headers in the json mock files? 

e.g. if we have
```
200 OK

{ response json object }
```

where would we put `{'Access-Control-Allow-Origin': '*'}` ?

This PR broke our use of the mock-api-server, we used the mock-api-server running in the background to code against. Our frontend calls started giving cors errors again (i had previously submitted a PR to have Access-Control-Allow-Origin always set, but i see that got removed).

**Pull request merged**
